# Generated by Django 6.0.2 on 2026-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_at',
        ),
    ]
